### ISSUE TITLE
Comment endpoints

### ISSUE THREAD

**Issue by marc0tjevp** [marc0tjevp/Avans-NoSQL#5]
Verb | Endpoint | Return | Body params | Description
-- | -- | -- | -- | --
POST | /threads/:id/comments | status | content | Needs unique identifier
POST | /comments/:id | status | content | Needs unique identifier
DELETE | /threads/:id/comments/:id | status |   | Deletes comment by id
GET | /threads/:id/comments/ | Array with comments |   | Get comments by thread id
PUT | /comments/:id | status | content | Edit a comment by id
GET | /comments/:id/karma | JSON with up and down |   | Get upvotes - downvotes
POST | /comments/:id/karma/up | status |   | Adds upvote to comment
POST | /comments/:id/karma/down | status |   | Adds downvote to comment

**Comment by MrSpaceblaze** [comment]
Moeten we voor de thread specifiek een id ophalen voor de comments als we hem willen aanpassen, en als we er karma aan willen toevoegen?

**Comment by marc0tjevp** [comment]
Maybe we can get the Thread Id only since it is stored in the comments table as ObjectId. For karma, not sure yet.
